behaviors:
  Asteriods:
    trainer_type: ppo
    hyperparameters:
      batch_size: 1024
      buffer_size: 10240
      learning_rate: 0.0003
      beta: 0.005
      epsilon: 0.2
      lambd: 0.959
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 128
      num_layers: 2
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    max_steps: 20000000
    time_horizon: 128
    summary_freq: 20000
environment_parameters:
  asteriod_spawn_rate:
    curriculum:
      - name: Lesson0 # The '-' is important as this is a list
        completion_criteria:
          measure: reward
          behavior: Asteriods
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 0.5
        value: 15
      - name: Lesson1 # This is the start of the second lesson
        completion_criteria:
          measure: reward
          behavior: Asteriods
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 1.5
        value: 10
      - name: Lesson2
        completion_criteria:
          measure: reward
          behavior: Asteriods
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 1.85
        value: 8
      - name: Lesson3
        value: 5
  asteriod_max_size:
    curriculum:
      - name: Lesson0 # The '-' is important as this is a list
        completion_criteria:
          measure: reward
          behavior: Asteriods
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 0.5
        value: 1
      - name: Lesson1 # This is the start of the second lesson
        completion_criteria:
          measure: reward
          behavior: Asteriods
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 1.5
        value: 1.25
      - name: Lesson2
        completion_criteria:
          measure: reward
          behavior: Asteriods
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 1.85
        value: 1.5
      - name: Lesson3
        value: 2
  asteriod_min_size:
    curriculum:
      - name: Lesson0 # The '-' is important as this is a list
        completion_criteria:
          measure: reward
          behavior: Asteriods
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 0.5
        value: 1
      - name: Lesson1 # This is the start of the second lesson
        completion_criteria:
          measure: reward
          behavior: Asteriods
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 1.5
        value: 0.9
      - name: Lesson2
        completion_criteria:
          measure: reward
          behavior: Asteriods
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 1.85
        value: 0.8
      - name: Lesson3
        value: 0.75
  allowed_asteriod_hits:
    curriculum:
      - name: Lesson0 # The '-' is important as this is a list
        completion_criteria:
          measure: reward
          behavior: Asteriods
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 0.5
        value: 10
      - name: Lesson1 # This is the start of the second lesson
        completion_criteria:
          measure: reward
          behavior: Asteriods
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 1.5
        value: 5
      - name: Lesson2
        completion_criteria:
          measure: reward
          behavior: Asteriods
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 1.85
        value: 3
      - name: Lesson3
        value: 1
  allowed_boundary_hits:
    curriculum:
      - name: Lesson0 # The '-' is important as this is a list
        completion_criteria:
          measure: reward
          behavior: Asteriods
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 0.5
        value: 25
      - name: Lesson1 # This is the start of the second lesson
        completion_criteria:
          measure: reward
          behavior: Asteriods
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 1.5
        value: 16
      - name: Lesson2
        completion_criteria:
          measure: reward
          behavior: Asteriods
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 1.85
        value: 10
      - name: Lesson3
        value: 1